import type { Property } from "./types";

export const GOOGLE_MAPS_API_KEY =
  "AIzaSyDnIoG0enyntSAu8pL_FolU8_zSbyLPzC4";

export const INDIAN_CITIES = [
  "Ahmedabad",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Pune",
  "Surat",
  "Rajkot",
  "Vadodara",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Jaipur",
  "Lucknow",
  "Indore",
  "Chandigarh",
];

export const AMENITIES_LIST = [
  "Swimming Pool",
  "Gymnasium",
  "Parking",
  "Security",
  "Power Backup",
  "Lift",
  "Garden",
  "Club House",
  "Sports Complex",
  "CCTV",
  "Intercom",
  "Fire Safety",
  "Water Harvesting",
  "Solar Panel",
  "Terrace",
  "Servant Quarter",
  "Modular Kitchen",
  "Vastu Compliant",
  "Gated Society",
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "p001",
    slug: "luxurious-4bhk-penthouse-vesu-surat",
    title: "Luxurious 4BHK Penthouse in Vesu",
    description:
      "An extraordinary penthouse with panoramic views, private terrace and world-class amenities.",
    listingType: "sale",
    propertyType: "penthouse",
    status: "active",
    isFeatured: true,
    price: 1.85,
    priceUnit: "cr",
    pricePerSqft: 6000,
    area: 3083,
    areaUnit: "sqft",
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    floor: 22,
    totalFloors: 24,
    address: "Vesu Main Road, Surat",
    locality: "Vesu",
    city: "Surat",
    state: "Gujarat",
    pincode: "395007",
    lat: 21.1413,
    lng: 72.7709,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    amenities: ["Swimming Pool", "Gymnasium", "Parking", "Security", "Terrace", "Lift", "CCTV"],
    agent: {
      id: "a001",
      name: "Rohan Mehta",
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80",
      verified: "verified",
      phone: "+91 98765 43210",
      rating: 4.8,
      reviewCount: 124,
    },
    postedAt: "2024-03-10",
    tags: ["Featured", "New Launch"],
  },
  {
    id: "p002",
    slug: "agricultural-land-aji-dam-rajkot",
    title: "Agricultural Land in Rajkot",
    description: "Prime agricultural land near Aji Dam with excellent water source and road access.",
    listingType: "sale",
    propertyType: "agricultural",
    status: "active",
    price: 80,
    priceUnit: "l",
    pricePerSqft: 200,
    area: 40000,
    areaUnit: "sqft",
    address: "Aji Dam Road, Rajkot",
    locality: "Aji Dam",
    city: "Rajkot",
    state: "Gujarat",
    pincode: "360001",
    lat: 22.3039,
    lng: 70.8022,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    ],
    amenities: ["Water Source", "Road Access"],
    agent: {
      id: "a002",
      name: "Arjun Patel",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
      verified: "verified",
      phone: "+91 98765 11111",
      rating: 4.5,
      reviewCount: 67,
    },
    postedAt: "2024-03-08",
  },
  {
    id: "p003",
    slug: "modern-3bhk-apartment-prahlad-nagar-ahmedabad",
    title: "Modern 3BHK Apartment in Prahlad Nagar",
    description:
      "Premium apartment in the heart of Ahmedabad's most sought-after corporate hub.",
    listingType: "sale",
    propertyType: "apartment",
    status: "active",
    isFeatured: true,
    price: 1.25,
    priceUnit: "cr",
    pricePerSqft: 5200,
    area: 2404,
    areaUnit: "sqft",
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    floor: 8,
    totalFloors: 15,
    address: "Prahlad Nagar, Ahmedabad",
    locality: "Prahlad Nagar",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380015",
    lat: 23.0395,
    lng: 72.5078,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: ["Swimming Pool", "Gymnasium", "Parking", "Security", "Club House", "CCTV", "Power Backup", "Lift"],
    agent: {
      id: "a003",
      name: "Priya Shah",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
      verified: "verified",
      phone: "+91 98765 22222",
      rating: 4.9,
      reviewCount: 203,
    },
    postedAt: "2024-03-12",
    tags: ["Hot Deal"],
  },
  {
    id: "p004",
    slug: "commercial-office-space-bkc-mumbai",
    title: "Commercial Office Space in BKC",
    description:
      "Grade A office space in Bandra Kurla Complex, Mumbai's prime business district.",
    listingType: "rent",
    propertyType: "commercial",
    status: "active",
    price: 4.5,
    priceUnit: "cr",
    pricePerSqft: 18000,
    area: 2500,
    areaUnit: "sqft",
    parking: 5,
    floor: 14,
    totalFloors: 30,
    address: "G Block, BKC, Mumbai",
    locality: "Bandra Kurla Complex",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400051",
    lat: 19.0596,
    lng: 72.8656,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    ],
    amenities: ["Parking", "Security", "CCTV", "Fire Safety", "Lift", "Power Backup", "Intercom"],
    agent: {
      id: "a004",
      name: "Vikram Joshi",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
      verified: "verified",
      rating: 4.7,
      reviewCount: 89,
    },
    postedAt: "2024-03-05",
  },
  {
    id: "p005",
    slug: "villa-koregaon-park-pune",
    title: "Elegant Villa in Koregaon Park",
    description:
      "A beautifully crafted independent villa with private garden and pool in Pune's most prestigious neighbourhood.",
    listingType: "sale",
    propertyType: "villa",
    status: "active",
    isFeatured: true,
    price: 12,
    priceUnit: "cr",
    pricePerSqft: 12000,
    area: 10000,
    areaUnit: "sqft",
    bedrooms: 5,
    bathrooms: 6,
    parking: 4,
    address: "Lane 5, Koregaon Park, Pune",
    locality: "Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    lat: 18.5362,
    lng: 73.8945,
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
    ],
    amenities: ["Swimming Pool", "Garden", "Parking", "Security", "CCTV", "Servant Quarter", "Modular Kitchen", "Vastu Compliant"],
    agent: {
      id: "a005",
      name: "Meera Kulkarni",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
      verified: "verified",
      rating: 5.0,
      reviewCount: 42,
    },
    postedAt: "2024-03-01",
    tags: ["Ultra Luxury"],
  },
  {
    id: "p006",
    slug: "2bhk-apartment-whitefield-bangalore",
    title: "2BHK Smart Apartment in Whitefield",
    description:
      "Modern smart home apartment near tech parks with excellent connectivity.",
    listingType: "rent",
    propertyType: "apartment",
    status: "active",
    price: 32,
    priceUnit: "k",
    pricePerSqft: 45,
    area: 1250,
    areaUnit: "sqft",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floor: 5,
    totalFloors: 12,
    address: "Whitefield Main Road, Bangalore",
    locality: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560066",
    lat: 12.9698,
    lng: 77.7500,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    amenities: ["Gymnasium", "Parking", "Security", "Swimming Pool", "Power Backup", "Lift", "CCTV"],
    agent: {
      id: "a006",
      name: "Suresh Nair",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
      verified: "verified",
      rating: 4.6,
      reviewCount: 158,
    },
    postedAt: "2024-03-14",
  },
  {
    id: "p007",
    slug: "plot-gandhinagar-sector-21",
    title: "Residential Plot in Gandhinagar Sector 21",
    description:
      "GIDC approved residential plot in planned sector with all utilities.",
    listingType: "sale",
    propertyType: "plot",
    status: "active",
    price: 2.5,
    priceUnit: "cr",
    pricePerSqft: 3500,
    area: 716,
    areaUnit: "sqm",
    address: "Sector 21, Gandhinagar",
    locality: "Sector 21",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "382021",
    lat: 23.2156,
    lng: 72.6369,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: ["Water Source", "Road Access"],
    agent: {
      id: "a007",
      name: "Hardik Desai",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80",
      verified: "verified",
      rating: 4.4,
      reviewCount: 91,
    },
    postedAt: "2024-02-28",
  },
  {
    id: "p008",
    slug: "3bhk-flat-marine-lines-mumbai",
    title: "Sea-View 3BHK Flat in Marine Lines",
    description:
      "Rare sea-facing apartment in South Mumbai with stunning Arabian Sea views.",
    listingType: "sale",
    propertyType: "apartment",
    status: "active",
    isFeatured: true,
    price: 22,
    priceUnit: "cr",
    pricePerSqft: 55000,
    area: 2100,
    areaUnit: "sqft",
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    floor: 16,
    totalFloors: 20,
    address: "Marine Lines, South Mumbai",
    locality: "Marine Lines",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400020",
    lat: 18.9438,
    lng: 72.8235,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    ],
    amenities: ["Parking", "Security", "CCTV", "Lift", "Garden", "Club House"],
    agent: {
      id: "a008",
      name: "Aisha Khan",
      avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80",
      verified: "verified",
      rating: 4.9,
      reviewCount: 176,
    },
    postedAt: "2024-03-03",
    tags: ["Sea Facing", "Premium"],
  },
  {
    id: "p009",
    slug: "studio-apartment-hsr-layout-bangalore",
    title: "Studio Apartment in HSR Layout",
    description:
      "Compact and well-designed studio ideal for young professionals.",
    listingType: "rent",
    propertyType: "studio",
    status: "active",
    price: 18,
    priceUnit: "k",
    pricePerSqft: 40,
    area: 450,
    areaUnit: "sqft",
    floor: 3,
    totalFloors: 8,
    address: "Sector 2, HSR Layout, Bangalore",
    locality: "HSR Layout",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560102",
    lat: 12.9082,
    lng: 77.6476,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    amenities: ["Security", "Power Backup", "Lift", "CCTV"],
    agent: {
      id: "a009",
      name: "Raj Kumar",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80",
      verified: "unverified",
      rating: 4.2,
      reviewCount: 34,
    },
    postedAt: "2024-03-15",
  },
  {
    id: "p010",
    slug: "farmhouse-lonavala-pune",
    title: "Weekend Farmhouse near Lonavala",
    description:
      "Sprawling farmhouse with scenic valley views, perfect for weekend getaways.",
    listingType: "sale",
    propertyType: "villa",
    status: "active",
    price: 4.5,
    priceUnit: "cr",
    pricePerSqft: 4500,
    area: 1,
    areaUnit: "acre",
    bedrooms: 4,
    bathrooms: 3,
    parking: 6,
    address: "Near Lonavala, Pune District",
    locality: "Lonavala",
    city: "Pune",
    state: "Maharashtra",
    pincode: "410401",
    lat: 18.7557,
    lng: 73.4066,
    images: [
      "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80",
    ],
    amenities: ["Garden", "Parking", "Water Harvesting", "Solar Panel", "Swimming Pool"],
    agent: {
      id: "a010",
      name: "Deepa Sharma",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
      verified: "verified",
      rating: 4.7,
      reviewCount: 58,
    },
    postedAt: "2024-02-20",
  },
  {
    id: "p011",
    slug: "commercial-showroom-cg-road-ahmedabad",
    title: "Prime Showroom on CG Road",
    description:
      "Ground floor showroom on Ahmedabad's most prominent commercial street.",
    listingType: "rent",
    propertyType: "commercial",
    status: "active",
    price: 1.8,
    priceUnit: "l",
    pricePerSqft: 300,
    area: 6000,
    areaUnit: "sqft",
    floor: 0,
    address: "CG Road, Navrangpura, Ahmedabad",
    locality: "CG Road",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380009",
    lat: 23.0285,
    lng: 72.5618,
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    ],
    amenities: ["Parking", "Security", "CCTV", "Power Backup"],
    agent: {
      id: "a011",
      name: "Nilesh Agarwal",
      avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&q=80",
      verified: "verified",
      rating: 4.5,
      reviewCount: 112,
    },
    postedAt: "2024-03-09",
  },
  {
    id: "p012",
    slug: "3bhk-villa-bopal-ahmedabad",
    title: "Row House Villa in Bopal",
    description:
      "Gated community row house with modern design and premium finishes.",
    listingType: "sale",
    propertyType: "villa",
    status: "active",
    price: 1.1,
    priceUnit: "cr",
    pricePerSqft: 4800,
    area: 2300,
    areaUnit: "sqft",
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    address: "Bopal, Ahmedabad",
    locality: "Bopal",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380058",
    lat: 23.0345,
    lng: 72.4664,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    amenities: ["Gymnasium", "Parking", "Security", "Garden", "Gated Society", "CCTV", "Club House"],
    agent: {
      id: "a012",
      name: "Kavya Reddy",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80",
      verified: "verified",
      rating: 4.8,
      reviewCount: 79,
    },
    postedAt: "2024-03-11",
    tags: ["Gated Community"],
  },
  {
    id: "p013",
    slug: "affordable-1bhk-ulwe-navi-mumbai",
    title: "1BHK Apartment in Ulwe, Navi Mumbai",
    description:
      "Affordable new construction apartment near Navi Mumbai airport zone.",
    listingType: "sale",
    propertyType: "apartment",
    status: "active",
    price: 42,
    priceUnit: "l",
    pricePerSqft: 6200,
    area: 677,
    areaUnit: "sqft",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    floor: 6,
    totalFloors: 18,
    address: "Ulwe, Navi Mumbai",
    locality: "Ulwe",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "410206",
    lat: 18.9897,
    lng: 73.0298,
    images: [
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&q=80",
    ],
    amenities: ["Parking", "Security", "Lift", "Power Backup"],
    agent: {
      id: "a013",
      name: "Rahul Bose",
      avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=100&q=80",
      verified: "verified",
      rating: 4.3,
      reviewCount: 45,
    },
    postedAt: "2024-03-13",
  },
  {
    id: "p014",
    slug: "office-space-cybercity-hyderabad",
    title: "IT Office Space in HITEC City",
    description:
      "Grade A+ IT/ITeS office space in Hyderabad's flourishing tech corridor.",
    listingType: "rent",
    propertyType: "commercial",
    status: "active",
    isFeatured: true,
    price: 2.5,
    priceUnit: "cr",
    pricePerSqft: 8500,
    area: 2940,
    areaUnit: "sqft",
    parking: 8,
    floor: 9,
    totalFloors: 22,
    address: "HITEC City, Madhapur, Hyderabad",
    locality: "HITEC City",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
    lat: 17.4477,
    lng: 78.3760,
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
    ],
    amenities: ["Parking", "Security", "CCTV", "Fire Safety", "Lift", "Power Backup", "Intercom"],
    agent: {
      id: "a014",
      name: "Sanjay Rao",
      avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&q=80",
      verified: "verified",
      rating: 4.6,
      reviewCount: 67,
    },
    postedAt: "2024-02-25",
  },
  {
    id: "p015",
    slug: "4bhk-duplex-south-delhi",
    title: "4BHK Duplex in South Delhi",
    description:
      "Magnificent duplex apartment in Delhi's most exclusive residential enclave.",
    listingType: "sale",
    propertyType: "apartment",
    status: "active",
    isFeatured: true,
    price: 8.5,
    priceUnit: "cr",
    pricePerSqft: 28500,
    area: 2982,
    areaUnit: "sqft",
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    floor: 10,
    totalFloors: 12,
    address: "Vasant Vihar, South Delhi",
    locality: "Vasant Vihar",
    city: "Delhi",
    state: "Delhi",
    pincode: "110057",
    lat: 28.5672,
    lng: 77.1564,
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    amenities: ["Swimming Pool", "Gymnasium", "Parking", "Security", "Club House", "Garden", "CCTV", "Gated Society"],
    agent: {
      id: "a015",
      name: "Neha Kapoor",
      avatar: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=100&q=80",
      verified: "verified",
      rating: 4.9,
      reviewCount: 231,
    },
    postedAt: "2024-03-07",
    tags: ["Luxury", "Duplex"],
  },
];

// ─── Utility Functions ────────────────────────────────────────────────────────

export function formatPrice(price: number, unit: string): string {
  if (unit === "cr") {
    return `₹${price} Cr`;
  } else if (unit === "l") {
    return `₹${price} L`;
  } else if (unit === "k") {
    return `₹${price}K/mo`;
  } else if (unit === "month") {
    return `₹${price.toLocaleString()}/mo`;
  }
  return `₹${price}`;
}

export function formatMapPrice(price: number, unit: string): string {
  if (unit === "cr") return `₹${price}Cr`;
  if (unit === "l") return `₹${price}L`;
  if (unit === "k") return `₹${price}K`;
  return `₹${price}`;
}

export function formatArea(area: number, unit: string): string {
  const formatted = area >= 1000 ? area.toLocaleString() : area;
  return `${formatted} ${unit}`;
}

export function getPropertyTypeBadgeColor(type: string): string {
  const colors: Record<string, string> = {
    residential: "bg-blue-50 text-blue-700 border-blue-100",
    commercial: "bg-purple-50 text-purple-700 border-purple-100",
    agricultural: "bg-emerald-50 text-emerald-700 border-emerald-100",
    plot: "bg-amber-50 text-amber-700 border-amber-100",
    villa: "bg-rose-50 text-rose-700 border-rose-100",
    apartment: "bg-sky-50 text-sky-700 border-sky-100",
    penthouse: "bg-indigo-50 text-indigo-700 border-indigo-100",
    studio: "bg-teal-50 text-teal-700 border-teal-100",
  };
  return colors[type] || "bg-gray-50 text-gray-700 border-gray-100";
}
